apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dotnet-deploy
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadyexh1779-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadyexh1779-tenant-component
    app.kubernetes.io/part-of: loadyexh1779-tenant-app
  name: loadyexh1779-tenant-component
  namespace: loadyexh1779-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: devfile-dotnet-deploy
    app.kubernetes.io/instance: loadyexh1779-tenant-component
  type: LoadBalancer
status:
  loadBalancer: {}
